<template>
  <div class="ui fluid container">
    <div class="ui middle aligned equal width stackable grid">
      <div class="four wide column large screen only">
        <img class="leftAva" src="../assets/genji.png" alt="">
      </div>
      <div class="centered center aligned sixteen wide mobile sixteen wide tablet eight wide computer column">
        <div class="row btm">
          <div class="column">
            <span class="title">R</span>
            <img class="rock" src="../assets/rock-font.png" style="">
            <span class="title space">CK</span>
            <span class="title">P</span>
            <img class="paper" src="../assets/paper-font.png" style="">
            <span class="title space">PER</span>
            <span class="title">S</span>
            <img class="scissors" src="../assets/scissors-font.png" style="">
            <span class="title">ISSORS</span>
          </div>
        </div>

        <div class="row btm">
          <div class="column">
            <h1 class="ui header">Select Room</h1>
            <button class="ui red button" @click="play">Room 1</button>
            <button class="ui orange button">Room 2</button>
            <button class="ui yellow button">Room 3</button>
            <button class="ui olive button">Room 4</button>
            <button class="ui green button">Room 5</button>
            <button class="ui teal button">Room 6</button>
            <button class="ui blue button">Room 7</button>
            <button class="ui violet button">Room 8</button>
            <button class="ui purple button">Room 9</button>
            <button class="ui pink button">Room 10</button>
            <button class="ui brown button">Room 11</button>
            <button class="ui grey button">Room 12</button>
          </div>
        </div>

        <div class="row btm">
          <div class="column">
            <i class="huge link icons vibrate-2" @click="logout">
              <i class="big thin red circle icon"></i>
              <i class="red power icon"></i>
            </i>
          </div>
        </div>
      </div>

      <div class="four wide column large screen only">
        <img src="../assets/ikaruga.png" alt="">
      </div>
    </div>
  </div>
</template>

<script>
import firebase from 'firebase'
export default {
  name: 'LobbyRoom',
  methods: {
    play: function () {
      this.$router.push('/play')
    },
    logout: function () {
      firebase.auth().signOut()
      .then(() => {
        this.$router.replace('/login')
      }).catch(error => {
        console.log(error)
        alert('Oops!!! ' + error)
      })
    }
  }
}
</script>

<style scoped>
  .vibrate-2 {
    -webkit-animation: vibrate-2 0.3s linear infinite both;
            animation: vibrate-2 0.3s linear infinite both;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2018-1-12 8:51:56
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation vibrate-2
  * ----------------------------------------
  */
  @-webkit-keyframes vibrate-2 {
    0% {
      -webkit-transform: translate(0);
              transform: translate(0);
    }
    20% {
      -webkit-transform: translate(2px, -2px);
              transform: translate(2px, -2px);
    }
    40% {
      -webkit-transform: translate(2px, 2px);
              transform: translate(2px, 2px);
    }
    60% {
      -webkit-transform: translate(-2px, 2px);
              transform: translate(-2px, 2px);
    }
    80% {
      -webkit-transform: translate(-2px, -2px);
              transform: translate(-2px, -2px);
    }
    100% {
      -webkit-transform: translate(0);
              transform: translate(0);
    }
  }
  @keyframes vibrate-2 {
    0% {
      -webkit-transform: translate(0);
              transform: translate(0);
    }
    20% {
      -webkit-transform: translate(2px, -2px);
              transform: translate(2px, -2px);
    }
    40% {
      -webkit-transform: translate(2px, 2px);
              transform: translate(2px, 2px);
    }
    60% {
      -webkit-transform: translate(-2px, 2px);
              transform: translate(-2px, 2px);
    }
    80% {
      -webkit-transform: translate(-2px, -2px);
              transform: translate(-2px, -2px);
    }
    100% {
      -webkit-transform: translate(0);
              transform: translate(0);
    }
  }


  .title {
    font-size: 50px;
    font-weight: 600;
  }

  .space {
    padding-right: 30px;
  }

  .rock {
    position: relative;
    top: 8px;
  }

  .paper {
    position: relative;
    top: 14px;
  }

  .scissors {
    position: relative;
    top: 5px;
  }

  .btm {
    padding-bottom: 50px !important;
  }

  .ui.middle.aligned.equal.width.stackable.grid {
    height: 100vh;
  }

  .ui.button {
    width: 160px;
    margin: .25rem;
  }

  .leftAva {
    max-height: 750px;
    position: absolute;
    z-index: -1;
    top: -345px;
    right: -204px;
  }
</style>
